---
- hosts: app_nodes
  become: yes
  vars:
    JRE_RPM_URL: https://corretto.aws/downloads/latest/amazon-corretto-11-x64-al2-jre.rpm
    APP_ARTIFACT_URL: https://uek-krakow.s3-eu-west-1.amazonaws.com/pp5/application.jar
    APP_DIR: /opt/ecommerce
    APP_USER: ecommerce
    APP_PORT: 5000
  tasks:
    - name: "Install jre"
      yum:
        name: "{{ JRE_RPM_URL }}"
        state: present
    - name: "Ensure app dir exist"
      file:
        path: "{{ APP_DIR }}"
        state: directory
    - name: "Download app arifact"
      get_url:
        url: "{{ APP_ARTIFACT_URL }}"
        dest: "{{ APP_DIR ~ '/application.jar'}}"
    - name: "Create user for my app"
      user:
        name: "{{ APP_USER }}"
        state: present
    - name: "Place service config"
      template:
        src: ~/files/ecommerce.service
        dest: /etc/systemd/system/ecommerce.service
    - name: "Start my app"
      systemd:
        name: ecommerce
        enabled: yes
        state: started
        daemon_reload: yes
  